#! /bin/sh

mkdir tarea3.tmp
cd tarea3.tmp
curl https://raw.githubusercontent.com/Master2uiroga/progra1/master/Tarea%203/Makefile >> Makefile
curl https://raw.githubusercontent.com/Master2uiroga/progra1/master/Tarea%203/Tarea3.c >> Tarea3.c
make
./Tarea3
make clean
cd ..
rm -rf tarea3.tmp
