#! /bin/sh

mkdir tarea3.tmp
cd tarea3.tmp
curl https://github.com/Master2uiroga/progra1/raw/master/Tarea%203/Makefile -O Makefile
curl https://github.com/Master2uiroga/progra1/blob/master/Tarea%203/Tarea3.c
make
./Tarea3
make clean
cd ..
rm -rf tarea3.tmp
